<%@ Page Title="" Language="C#" MasterPageFile="~/Page.Master" AutoEventWireup="true" CodeBehind="Home.aspx.cs" Inherits="TermProject.Home" %>

<asp:Content ID="Content1" ContentPlaceHolderID="cphHead" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="cphBody" runat="server">
    <style>
        .center {
            text-align: center;
        }
    </style>
    <asp:Label ID="lblStatus" Class="lblStatus" runat="server" />
    <h2>WebService Method Test Page</h2>
    <br />
    <div class="row">
        <div class="col-lg-8">

            <div class="col-md-4">
            </div>
            <div class="col-md-4">
                <h3>Upload a file</h3>
                <asp:Label ID="lblFileError" runat="server" Text="" Visible="false"></asp:Label>&nbsp;<asp:Label ID="lblTest" runat="server" Text=""></asp:Label><br />
                <asp:FileUpload ID="FileUpload1" runat="server" /><br />
                <asp:Button ID="btnUpload" runat="server" Text="Submit" OnClick="btnUpload_Click" />
            </div>
            <div class="col-md-4">
            </div>
            <!--end row 1-->
            <div class="row">
                <div class="col-md-12">
                    <h3>View & Delete a File</h3>
                    <asp:GridView ID="gvUserFiles" runat="server" AutoGenerateDeleteButton="True" AutoGenerateColumns="False" AutoGenerateEditButton="True" AutoGenerateSelectButton="True" OnRowCancelingEdit="gvUserFiles_RowCancelingEdit" OnRowDeleting="gvUserFiles_RowDeleting" OnRowEditing="gvUserFiles_RowEditing" OnRowUpdating="gvUserFiles_RowUpdating" OnSelectedIndexChanged="gvUserFiles_SelectedIndexChanged">
                        <Columns>
                            <asp:BoundField DataField="FileName" HeaderText="File Name" SortExpression="fileName" />
                            <asp:BoundField DataField="fileSize" HeaderText="File Size" ReadOnly="True" />
                            <asp:BoundField DataField="FileData" HeaderText="File" ReadOnly="True" SortExpression="FileData" />
                            <asp:BoundField DataField="FileType" HeaderText="File Type" ReadOnly="True" />
                        </Columns>
                    </asp:GridView>
                </div>
            </div>
            <!--end row 2-->
            <div class="row center">
                <div class="col-lg-12">
                    <h3>Account Info - Edit or Delete Fields</h3>
                    <div class="col-lg-12">

                        <asp:Label ID="lblAccountError" runat="server" Text=""></asp:Label>&nbsp;

                        <asp:ValidationSummary ID="valErrorList" runat="server" ForeColor="#CC0000"/>
                        <br />

                        <asp:Label ID="lblName" runat="server" Text="Full Name: "></asp:Label><asp:TextBox ID="txtName" runat="server"></asp:TextBox>&nbsp;
                        <asp:RequiredFieldValidator ID="RequiredFieldValidator1" runat="server" ErrorMessage="Name cannot be empty" ControlToValidate="txtName"></asp:RequiredFieldValidator>&nbsp;
                        
                        <asp:Label ID="Label2" runat="server" Text="Total File size"></asp:Label> &nbsp;
                        <asp:TextBox ID="txtUsedSC" runat="server" ReadOnly="True"></asp:TextBox>
                        <br />
                        
                        <asp:Label ID="lblEmail" runat="server" Text="Email: "></asp:Label><asp:TextBox ID="txtEmail" TextMode="Email" runat="server" Height="27px"></asp:TextBox>&nbsp;
                        <asp:RequiredFieldValidator ID="RequiredFieldValidator2" runat="server" ErrorMessage="Email cannot be empty" ControlToValidate="txtEmail"></asp:RequiredFieldValidator>
                        
                        &nbsp;
                        <asp:Label ID="Label1" runat="server" Text="Password"></asp:Label>
                        &nbsp;<asp:TextBox ID="txtPW" runat="server"></asp:TextBox>
                        <asp:RequiredFieldValidator ID="RequiredFieldValidator3" runat="server" ErrorMessage="Password cannot be empty" ControlToValidate="txtPW"></asp:RequiredFieldValidator>
                        <br />
                        
                        <asp:Label ID="lblCapacity" runat="server" Text="Storage Capacity "></asp:Label><asp:TextBox ID="txtCapacity" runat="server"></asp:TextBox>
                        <asp:RequiredFieldValidator ID="RequiredFieldValidator4" runat="server" ErrorMessage="Capacity cannot be empty" ControlToValidate="txtCapacity"></asp:RequiredFieldValidator>
                        <br />
                        <br />
                        
                        <asp:Button ID="btnAccount" runat="server" Text="Submit" OnClick="btnAccount_Click" />
                        <br />
                    </div>
                </div>
            </div>
            <!--end row 3-->

            <div class="row">
                <div class="col-lg-12">
                    <h3>File Transactions</h3>
                    <asp:GridView ID="gvTransactions" runat="server" OnPageIndexChanged="gvTransactions_PageIndexChanged" OnRowCancelingEdit="gvTransactions_RowCancelingEdit" OnRowDeleting="gvTransactions_RowDeleting" OnRowUpdating="gvTransactions_RowUpdating">
                        <Columns>
                            <asp:BoundField DataField="Name" HeaderText="Name" SortExpression="Name" />
                            <asp:BoundField DataField="LoginID" HeaderText="Email" SortExpression="LoginID" />
                            <asp:BoundField DataField="HashedPassword" HeaderText="Password" SortExpression="HashedPassword" />
                            <asp:BoundField DataField="StorageCapacity" HeaderText="Storage Capacity " ReadOnly="True" SortExpression="StorageCapacity" />
                            <asp:BoundField DataField="StorageUsed" HeaderText="Storage Used" ReadOnly="True" SortExpression="StorageUsed" />
                            <asp:BoundField DataField="Account" HeaderText="Account" ReadOnly="True" SortExpression="Account" />
                        </Columns>
                    </asp:GridView>
                </div>
            </div>
            <!--end row 4-->
        </div>
    </div>
</asp:Content>
