<%@ Page Title="" Language="C#" MasterPageFile="~/Page.Master" AutoEventWireup="true" CodeBehind="Home.aspx.cs" Inherits="TermProject.Home" %>

<asp:Content ID="Content1" ContentPlaceHolderID="cphHead" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="cphBody" runat="server">
    <style>
        .center{
            text-align:center;
        }
    </style>
    <asp:Label ID="lblStatus" Class="lblStatus" runat="server" />
    <h2>WebService Method Test Page</h2>
    <br />
    <div class="row">
        <div class="col-md-4">
            
        </div>
        <div class="col-md-4">
            <h3>Upload a file</h3>
            <asp:Label ID="lblFileError" runat="server" Text="" Visible="false"></asp:Label>&nbsp;<asp:Label ID="lblTest" runat="server" Text=""></asp:Label><br />
            <asp:FileUpload ID="FileUpload1" runat="server" /><br />
            <asp:Button ID="btnUpload" runat="server" Text="Submit" OnClick="btnUpload_Click" />
        </div>
        <div class="col-md-4">
            
        </div><!--end row 1-->
        <div class="row">
            <div class="col-md-12">
                <h3>View & Delete a File</h3>
                <asp:GridView ID="gvUserFiles" runat="server" AutoGenerateDeleteButton="True">

                </asp:GridView>
            </div>
        </div><!--end row 2-->
        <div class="row center">
            <div class="col-lg-12">
                <h3>Account Info</h3>
                <div class="col-lg-12">
                    <asp:Label ID="lblFN" runat="server" Text="First Name: "></asp:Label><asp:TextBox ID="TextBox1" runat="server"></asp:TextBox><br />
                    <asp:Label ID="lblLN" runat="server" Text="Last Name: "></asp:Label><asp:TextBox ID="TextBox2" runat="server"></asp:TextBox><br />
                    <asp:Label ID="Label1" runat="server" Text="Email: "></asp:Label><asp:TextBox ID="TextBox3" runat="server"></asp:TextBox><br />
                    <asp:Label ID="Label2" runat="server" Text="Storage Capacity "></asp:Label><asp:TextBox ID="TextBox4" runat="server"></asp:TextBox>
                    <br />
                    <asp:Button ID="btnAccount" runat="server" Text="Submit" />
                    <br />

                </div>
            </div>
        </div><!--end row 3-->
        <div class="row">
            <div class="col-lg-12">
                <h3>File Transactions</h3>
                <asp:GridView ID="gvTransactions" runat="server">

                </asp:GridView>
            </div>
        </div><!--end row 4-->
    </div>

</asp:Content>
